### ISSUE TITLE
Learn.co site treats this lesson as a lab, rather than a readme

### ISSUE THREAD

**Issue by throwawaythekey** [learn-co-students/traversing-nested-objects-js-intro-000#3]
i.e., it wants you to fork and submit, even though there are no tests. The expected behavior would be that the site displays a "mark as read" button instead.

Attempting to fork this lab using `learn open traversing-nested-objects-js-intro-000` in the Learn IDE fails with "It looks like this lesson is a Readme. Plese open it in your browser." (Note the editing error in error message).

**Comment by throwawaythekey** [comment]
issue has been raised on canonical version, closing here.

**Comment by throwawaythekey** [comment]
On second thought, maybe this is an appropriate venue? This issue may be specific to users on the Introduction To Javascript track. For cross-reference, see my comment on learn-co-curriculum/traversing-nested-objects#8

**Comment by AnnJohn** [comment]
thanks @throwawaythekey for raising the issue. We changed it so that it'll render as a readme instead of a lab so it should be good moving forward. thanks!

**Comment by cqlanus** [comment]
I'm still seeing this as a Lab instead of a readme.
![screen shot 2016-08-28 at 11 28 32 am](https://cloud.githubusercontent.com/assets/7458958/18035846/9c798912-6d12-11e6-8eb0-8c0ae7edb039.png)
